### ISSUE TITLE
Font Issue

### ISSUE THREAD

**Issue by Spencer1337** [mvs-org/mvs-live#3]
There appears to be an issue with the font in Chrome and IE web browsers causing extra spaces following an apostrophe. Issue appeared on 2 separate computers, no issues on mobile. No issues with text in html. Problem appeared to be resolved when using a different font. 

![etpfont](https://user-images.githubusercontent.com/36527158/36451678-b59d611e-1646-11e8-8602-0cc642a305fe.PNG)
![etpfont2](https://user-images.githubusercontent.com/36527158/36451683-b89105c4-1646-11e8-9119-c7e316dff2a7.PNG)
![etpfont3](https://user-images.githubusercontent.com/36527158/36451687-ba032f04-1646-11e8-8bb4-b02a58d0aa45.PNG)

**Comment by betachen** [comment]
@Spencer1337 Yes, We will release new version of official website.
Thanks, @Spencer1337

**Comment by betachen** [comment]
mvs.org changed. then closed.
