### ISSUE TITLE
Please revert the website to this commit

### ISSUE THREAD

**Issue by NotoriousPyro** [mvs-org/mvs-live#7]
Those of us in Telegram were impressed with this commit, only to find the most improved aspects had been removed.

Please revert to commit c6c0b7ca53b7c9c86bcd93189b669d3aa7bbb40d.

![photo_2018-03-09_21-51-32](https://user-images.githubusercontent.com/706132/37241915-ef1dc634-2458-11e8-8912-a259afd6ae2d.jpg)

**Comment by kristheclueless** [comment]
Please guys, revert to the commit from a week ago. There current one is very bad!

**Comment by alk0holix** [comment]
It seems to be some kind of bug in the desktop version of the site, on mobile its looking good.

**Comment by betachen** [comment]
Good point.
we will do that.

**Comment by DiplomaticImmunity** [comment]
@betachen 
If you could put that picture in mobile instead of the current one would be better. since the video play on the website is good it was just bugged for some people who used firefox/mac/etc so it looked point blank

**Comment by betachen** [comment]
Thx.
we had done.
